feat: add address table look up and withdraw auction house treasury commands
holaplex/reward-center-program pull request #32
Opened 2022-12-07 04:02 UTC by sunguru98

The CLI now has two commands 
1. create-atl
2. withdraw-ah

create-atl makes sure to create an address table and add the mentioned address @ #31, although I wasn't sure regarding the `token_account` address @kespinola  

Example tx for ATL creation - https://explorer.solana.com/tx/5iAR4yaZ2U3Z71L75Z542r6gWg73F9xxBRARfzgNmCEq6UnCDkHXuLD3zGp7z4XJunKHgKXW16zRQqDrzmNPjkVS?cluster=devnet

withdraw-ah basically calls an instruction from Auction House naming `WithdrawTreasury`

Closes #31 and #30

2022-12-08 09:25 UTC, kespinola requested changes

2022-12-08 09:26 UTC, sunguru98 commented on cli/src/commands/withdraw_auction_house.rs
> +    let instructions: Vec<Instruction> = vec![withdraw_from_treasury(
Oh, totally forgot. Adding the changes.

2022-12-09 08:21 UTC, kespinola commented on cli/src/commands/withdraw_auction_house.rs
> +
Don't always have to deduct rent_exemption only if the amount would leave the treasury under rent exemption.

2022-12-09 09:20 UTC, kespinola approved these changes

2022-12-09 09:20 UTC, merged